language: bash
env:
  global:
    - MAINTAINER="Ryan Lieu<github-benzBrake@woai.ru>"
  matrix:
    - DOCKER_REPO=benzbrake/goflyway
      DOCKER_TAG=1.0
      BUILD_DIRECTORY=goflyway
      BUILD_ARGS_FILE=build_args_v1
    - DOCKER_REPO=benzbrake/goflyway
      DOCKER_TAG=2.0
      TAG_LATEST=true
      BUILD_DIRECTORY=goflyway

sudo: required
  
services:
  - docker

before_script:
  - chmod +x ./hooks/*.sh

script:
  - ./hooks/build.sh

after_success:
  - ./hooks/upload.sh

branches:
  only:
    - master

notifications:
  email: false